### PR TITLE
Feature: Add default escape to data()

### PR DESCRIPTION
**Pull request by ceesvanegmond**

### CODE REVIEW

**Review by mzur — CHANGES_REQUESTED** [review]
I'd like to allow users to choose not to escape the data. Security should be the default but should not prevent legitimate use cases (e.g. intentionally uploading and storing HTML).

Also you could use the already included `encodeField` function instead of `Escape`. I'd use the Toolkit, too, but it doesn't offer an `unescape` function.

**Comment by ceesvanegmond** [comment]
@mzur What about this?

**Review by mzur — CHANGES_REQUESTED** [review]
Looks good. Please also update the tests. `testDecodeField` must be updated for the new behavior. Please also add a test case for `$escape=false`. In `testOld` the value is double-encoded somehow but it should only be encoded once.

**Comment by ceesvanegmond** [comment]
@mzur Sorry man. Holiday and stuff. Will try finishing this PR today

**Comment by ceesvanegmond** [comment]
@mzur Just pushed the tests that pass. Note that in the `old()` method I removed the `encodeField` because it's already encoded before the flasbag.

**Comment by ceesvanegmond** [comment]
@mzur Saw my latest commit?

**Comment by mzur** [comment]
Yes, will review when I have time, thanks!

**Comment by mzur** [comment]
Looks good. Thanks.

**Review by mzur — APPROVED** [review]

**Pull request merged**
