### PR TITLE
Handle nested data arrays

### PR DESCRIPTION
**Pull request by nilshoerrmann**
If you are updating structure fields from the frontend using Kirby Uniform, content will be nested, e. g. `<input name="structure[field][]" />`. Therefore, the second level of the data array will also be an array. Currently, the form handler expects this to be a string and throws an error.

### CODE REVIEW

**Review by mzur — CHANGES_REQUESTED** [review]
Thanks! Please merge the current `master` so the tests are working again and add a new test case for this.

**Comment by nilshoerrmann** [comment]
I merged in the latest changes but I have no idea how to write a test case for this change.

**Comment by mzur** [comment]
You can duplicate [this test](https://github.com/mzur/kirby-form/blob/89250e5fcd0dec98f0fc5fa80464740fdc2cb610/tests/FormTest.php#L135-L142) and change the input data to nested arrays.

**Comment by nilshoerrmann** [comment]
Done!

**Review by mzur — APPROVED** [review]
Great, thanks!

**Pull request merged**
